--- 
- name: Install Docker and deploy Docker image 
  hosts: all 
  become: true 
 
  vars: 
    app_image: "vivekkallate/staragilefinanceproject:v1" 
    container_name: "c01" 
    host_port: 8081
    container_port: 8081
 
  tasks: 
    - name: Install prerequisite packages 
      ansible.builtin.apt: 
        update_cache: yes 
        name: 
          - apt-transport-https 
          - ca-certificates 
          - curl 
          - software-properties-common 
          - python3-pip 
 
    - name: Add Docker GPG key 
      ansible.builtin.apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present 
 
    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker packages 
      ansible.builtin.apt: 
        name: 
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
        state: present 
        update_cache: yes 
 
    - name: Pull application Docker image 
      community.docker.docker_image: 
        name: "{{ app_image }}" 
        source: pull 
 
    - name: Run the application container 
      community.docker.docker_container: 
        name: "{{ container_name }}" 
        image: "{{ app_image }}" 
        state: started 
        restart_policy: always 
        ports: 
          - "{{ host_port }}:{{ container_port }}"
